# Generated by Django 5.2.4 on 2025-07-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArebiaMejlis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('order_code', models.CharField(default='TEMP', help_text='Unique order reference', max_length=30, unique=True)),
                ('receive_order_at', models.CharField(blank=True, max_length=120)),
                ('completed_order_at', models.CharField(blank=True, max_length=120)),
                ('material_type', models.CharField(blank=True, max_length=60)),
                ('design_type', models.CharField(blank=True, max_length=60)),
                ('no_of_mekeda', models.PositiveIntegerField(default=0)),
                ('no_of_pillow', models.PositiveIntegerField(default=0)),
                ('uplift_or_height', models.CharField(blank=True, max_length=30)),
                ('room_size', models.FloatField()),
                ('room_shape', models.CharField(default='U', max_length=10)),
                ('price_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('app_front', models.CharField(blank=True, max_length=50)),
                ('remaining_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sides', models.JSONField()),
                ('segments', models.JSONField()),
                ('svg_file', models.FileField(blank=True, null=True, upload_to='orders/svg/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='orders/pdf/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
