# Generated by Django 5.2.4 on 2025-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arebia_mejlis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arebiamejlis',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='arebiamejlis/pdf/'),
        ),
        migrations.AlterField(
            model_name='arebiamejlis',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='arebiamejlis/svg/'),
        ),
    ]
