# Generated by Django 5.2.4 on 2025-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MejlisMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=100)),
                ('design_type', models.CharField(max_length=100)),
                ('no_of_mekeda', models.IntegerField()),
                ('no_of_pillow', models.IntegerField()),
                ('uplift_or_height', models.CharField(max_length=20)),
                ('room_size', models.IntegerField()),
                ('room_shape', models.CharField(max_length=20)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_table', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_name', models.CharField(max_length=20)),
                ('values', models.JSONField()),
            ],
        ),
    ]
