# Generated by Django 4.2.23 on 2025-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MejlisMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_made_from', models.CharField(max_length=100)),
                ('design_type', models.CharField(max_length=100)),
                ('no_of_mekeda', models.IntegerField()),
                ('no_of_pillow', models.IntegerField()),
                ('uplift_or_height', models.CharField(max_length=20)),
                ('room_size', models.IntegerField()),
                ('room_shape', models.CharField(max_length=20)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_table', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejlis_materials', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_name', models.CharField(max_length=20)),
                ('values', models.JSONField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='materials.mejlismaterial')),
            ],
        ),
    ]
