# Generated by Django 5.2.4 on 2025-08-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mejlismaterial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejlis_materials', to='order.order'),
        ),
        migrations.AddField(
            model_name='segment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='materials.mejlismaterial'),
        ),
    ]
