# Generated by Django 5.2.4 on 2025-08-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mejlismaterial',
            name='material_made_from',
            field=models.CharField(default='mdf', max_length=100),
            preserve_default=False,
        ),
    ]
