# Generated by Django 4.2.23 on 2025-08-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_mejlismaterial_material_made_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mejlismaterial',
            name='material_type',
        ),
    ]
