# Generated by Django 4.2.23 on 2025-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('material_type', models.CharField(blank=True, choices=[('mejlis', 'Mejlis'), ('sofa', 'Sofa'), ('bed', 'Bed'), ('kitchen_cabinet', 'Kitchen Cabinet'), ('cupboard', 'Cupboard'), ('tvstand', 'TV Stand')], max_length=50, null=True)),
                ('receive_order_at', models.DateField()),
                ('completed_order_at', models.DateField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('app_front', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('app_front_received_date', models.DateField(blank=True, null=True)),
                ('remaining_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('document_path', models.FileField(blank=True, null=True, upload_to='order_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
            ],
        ),
    ]
