# Generated by Django 5.2.4 on 2025-08-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('receive_order_at', models.DateField()),
                ('completed_order_at', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('app_front', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('app_front_received_date', models.DateField()),
                ('document_path', models.FileField(blank=True, null=True, upload_to='order_documents/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
            ],
        ),
    ]
