# Generated by Django 4.2.23 on 2025-08-28 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_created_at_order_status_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material_type',
            field=models.CharField(choices=[('mejlis', 'Mejlis'), ('sofa', 'Sofa'), ('bed', 'Bed'), ('kitchen_cabinet', 'Kitchen Cabinet'), ('cupboard', 'Cupboard'), ('tvstand', 'TV Stand')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
