# Generated by Django 4.2.23 on 2025-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='material_type',
            field=models.CharField(blank=True, choices=[('mejlis', 'Mejlis'), ('sofa', 'Sofa'), ('bed', 'Bed'), ('kitchen_cabinet', 'Kitchen Cabinet'), ('cupboard', 'Cupboard'), ('tvstand', 'TV Stand')], max_length=50, null=True),
        ),
    ]
